# Generated by Django 4.0.4 on 2022-04-30 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='content',
            new_name='body',
        ),
    ]
